export const PRODUCT_CATEGORIES = [
  "Granite",
  "Marble",
  "Onyx",
  "Travertine",
  "Quartzite",
  "Basalt",
  "Limestone",
  "Semi Precious",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

export type Product = {
  id: number;
  code: string;
  name: string;
  cat: string;
  stoneType?: string;
  size: string;
  image: string;
  heroImage: string;
  detailImage: string;
  finish: string;
  origin: string;
  colors: string;
  description?: string;
};

export const PRODUCTS: Product[] = [
  {
    "id": 1,
    "code": "KK-C-101",
    "name": "Persian Bianco",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "285 × 185",
    "image": "images/stones/chini-bianco.webp",
    "heroImage": "images/stones/chini-bianco.webp",
    "detailImage": "images/stones/chini-bianco-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "White, Grey",
    "description": "High quality Iranian crystal stone with light grey veins, highly popular for interior flooring."
  },
  {
    "id": 2,
    "code": "KK-G-102",
    "name": "Persian Zebra",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "300 × 180",
    "image": "images/prod_img_1.jpg",
    "heroImage": "images/inprod_img_1.jpg",
    "detailImage": "images/inprod_img_2.jpg",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Black, White",
    "description": "Highly durable black granite with white lines, suitable for indoor/outdoor spaces, kitchen countertops, and bathrooms."
  },
  {
    "id": 3,
    "code": "KK-G-103",
    "name": "Native Black Super Rock",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "285 × 160",
    "image": "images/stones/native-black.webp",
    "heroImage": "images/stones/native-black.webp",
    "detailImage": "images/stones/native-black-detail.webp",
    "finish": "Rock Finish / 3D Textured",
    "origin": "Iranian",
    "colors": "Black",
    "description": "Processed with rock design creating a 3D texture and distinct crystal geometric shapes that reflect light impressively."
  },
  {
    "id": 4,
    "code": "KK-G-104",
    "name": "Tuyserkan",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "311 × 161",
    "image": "images/stones/tuyserkan.webp",
    "heroImage": "images/stones/tuyserkan.webp",
    "detailImage": "images/stones/tuyserkan-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Black, Dark Grey",
    "description": "Chemical-resistant Iranian granite ideal for walls, stairs, courtyard floors, parking lots, and building facades."
  },
  {
    "id": 5,
    "code": "KK-Q-105",
    "name": "Black Horse Rock",
    "cat": "Quartzite",
    "stoneType": "Quartzite",
    "size": "320 × 190",
    "image": "images/stones/black-horse-rock.webp",
    "heroImage": "images/stones/black-horse-rock.webp",
    "detailImage": "images/stones/black-horse-rock-detail.webp",
    "finish": "Rock Finish",
    "origin": "Brazilian",
    "colors": "Black, Grey, White",
    "description": "Brazilian quartzite processed with rock design featuring a 3D texture and crystal geometry that offers dazzling light reflection."
  },
  {
    "id": 6,
    "code": "KK-C-106",
    "name": "Silver Stream Rock",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "267 × 180",
    "image": "images/stones/silver-stream-rock.webp",
    "heroImage": "images/stones/silver-stream-rock.webp",
    "detailImage": "images/stones/silver-stream-rock-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Grey, Silver, Light Grey",
    "description": "Striking combination of deep and light shades. High polishability, compressive strength, and abrasion resistance. Excellent for bookmatch and fourmatch patterns."
  },
  {
    "id": 7,
    "code": "KK-G-107",
    "name": "Leathered Matrix",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "209 × 171",
    "image": "images/stones/leathered-matrix.webp",
    "heroImage": "images/stones/leathered-matrix.webp",
    "detailImage": "images/stones/leathered-matrix-detail.webp",
    "finish": "Matrix / 3D Textured",
    "origin": "Iranian",
    "colors": "Grey, Dark Grey, Black",
    "description": "Grey background with matrix processing. Features a 3D surface texture offering a modern look and natural feel. Suitable for interior and exterior walls, floors, facades, and stairs."
  },
  {
    "id": 8,
    "code": "KK-M-108",
    "name": "Turtle & NATO",
    "cat": "Marble",
    "stoneType": "Fossil Marble",
    "size": "280 × 185",
    "image": "images/stones/turtle-venato.webp",
    "heroImage": "images/stones/turtle-venato.webp",
    "detailImage": "images/stones/turtle-venato-detail.webp",
    "finish": "Honed / Polished",
    "origin": "African",
    "colors": "Brown, Beige, Dark Grey",
    "description": "Fossilized marble with a unique texture, perfectly suited for interior design."
  },
  {
    "id": 9,
    "code": "KK-C-109",
    "name": "Persian Maya",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "285 × 175",
    "image": "images/stones/persian-maya.webp",
    "heroImage": "images/stones/persian-maya.webp",
    "detailImage": "images/stones/persian-maya-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "White, Light Grey",
    "description": "One of the finest options for interior flooring."
  },
  {
    "id": 11,
    "code": "KK-G-111",
    "name": "Alpinus Granite",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "315 × 185",
    "image": "images/prod_img_10.jpg",
    "heroImage": "images/inprod_img_5.jpg",
    "detailImage": "images/inprod_img_0.jpg",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Cream, Brown, Black",
    "description": "Durable granite suitable for floors, walls, exterior facades, kitchens, and restrooms."
  },
  {
    "id": 12,
    "code": "KK-T-112",
    "name": "Red Travertine",
    "cat": "Travertine",
    "stoneType": "Travertine",
    "size": "258 × 150",
    "image": "images/stones/red-travertine.webp",
    "heroImage": "images/stones/red-travertine.webp",
    "detailImage": "images/stones/red-travertine-detail.webp",
    "finish": "Polished / Honed",
    "origin": "Iranian",
    "colors": "Red, Terracotta",
    "description": "Popular choice among builders for exterior facades and interior accent design."
  },
  {
    "id": 13,
    "code": "KK-C-113",
    "name": "Persian Panda",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "290 × 180",
    "image": "images/prod_img_12.jpg",
    "heroImage": "images/inprod_img_1.jpg",
    "detailImage": "images/inprod_img_2.jpg",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "White, Black",
    "description": "Unique pattern and color with high polishability. Suitable for bookmatch/fourmatch layouts in interiors, staircases, and risers."
  },
  {
    "id": 14,
    "code": "KK-Q-114",
    "name": "Copacabana",
    "cat": "Quartzite",
    "stoneType": "Quartzite",
    "size": "320 × 195",
    "image": "images/prod_img_13.jpg",
    "heroImage": "images/inprod_img_2.jpg",
    "detailImage": "images/inprod_img_3.jpg",
    "finish": "Polished",
    "origin": "Brazilian",
    "colors": "Black, White",
    "description": "Black stone with parallel white veins, applicable anywhere in the building to add a distinctive highlight."
  },
  {
    "id": 15,
    "code": "KK-M-115",
    "name": "Pietra Grey (Pietra/Lashtar)",
    "cat": "Marble",
    "stoneType": "Marble",
    "size": "280 × 170",
    "image": "images/prod_img_14.jpg",
    "heroImage": "images/inprod_img_3.jpg",
    "detailImage": "images/inprod_img_4.jpg",
    "finish": "Honed / Polished",
    "origin": "Iranian",
    "colors": "Grey, Charcoal, White Veins",
    "description": "Classic Iranian marble long favored in the building industry, mainly used in interior design."
  },
  {
    "id": 16,
    "code": "KK-M-116",
    "name": "3D Black",
    "cat": "Marble",
    "stoneType": "Marble",
    "size": "270 × 150",
    "image": "images/stones/3D-black.webp",
    "heroImage": "images/stones/3D-black.webp",
    "detailImage": "images/stones/3D-black-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Black, White, Gold",
    "description": "Black background with white and occasional golden veins. High polishability, good compressive strength, and low water absorption."
  },
  {
    "id": 17,
    "code": "KK-Q-117",
    "name": "Red Collins",
    "cat": "Quartzite",
    "stoneType": "Quartzite",
    "size": "310 × 185",
    "image": "images/prod_img_16.jpg",
    "heroImage": "images/inprod_img_5.jpg",
    "detailImage": "images/inprod_img_0.jpg",
    "finish": "Polished",
    "origin": "Brazilian",
    "colors": "Red, Multicolor",
    "description": "Vibrant colors with exceptional resistance to abrasion and acidic cleaners. Versatile for any building application."
  },
  {
    "id": 18,
    "code": "KK-S-118",
    "name": "Royal Black Wood",
    "cat": "Semi Precious",
    "stoneType": "Obsidian",
    "size": "260 × 150",
    "image": "images/stones/royal-blackwood.webp",
    "heroImage": "images/stones/royal-blackwood.webp",
    "detailImage": "images/stones/royal-blackwood-detail.webp",
    "finish": "Polished",
    "origin": "Chinese",
    "colors": "Black, Dark Brown",
    "description": "Rare, high-hardness obsidian stone ideal for luxury interior design."
  },
  {
    "id": 19,
    "code": "KK-G-119",
    "name": "Algae Hard",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "322 × 180",
    "image": "images/stones/Algae-hard.webp",
    "heroImage": "images/stones/Algae-hard.webp",
    "detailImage": "images/stones/Algae-hard-detail.webp",
    "finish": "Hard Polish",
    "origin": "Iranian",
    "colors": "Green, White",
    "description": "Durable Iranian granite suitable for facades and interior design."
  },
  {
    "id": 20,
    "code": "KK-G-120",
    "name": "Algae Cotton",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "320 × 175",
    "image": "images/stones/algae-cotton.webp",
    "heroImage": "images/stones/algae-cotton.webp",
    "detailImage": "images/stones/algae-cotton-detail.webp",
    "finish": "Textured / Chiseled Cotton",
    "origin": "Iranian",
    "colors": "Cream, Green",
    "description": "Granite crafted with custom tooling to achieve a fabric-like textile texture. Suitable for facades and interiors."
  },
  {
    "id": 21,
    "code": "KK-Q-121",
    "name": "Infinity Gold",
    "cat": "Quartzite",
    "stoneType": "Quartzite",
    "size": "250 × 180",
    "image": "images/stones/infinity-gold.webp",
    "heroImage": "images/stones/infinity-gold.webp",
    "detailImage": "images/stones/infinity-gold-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Gold, Black, Grey",
    "description": "Iranian quartzite suitable for facades, interior design, flooring, and kitchens."
  },
  {
    "id": 22,
    "code": "KK-C-122",
    "name": "Aligudarz Crystal",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "290 × 175",
    "image": "images/stones/aligoudarz.webp",
    "heroImage": "images/stones/aligoudarz.webp",
    "detailImage": "images/stones/aligoudarz-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "White, Light Grey",
    "description": "Light-toned crystal stone with excellent polishability, bringing a serene and calming ambiance to interiors."
  },
  {
    "id": 23,
    "code": "KK-B-123",
    "name": "Black Basalt",
    "cat": "Basalt",
    "stoneType": "Basalt",
    "size": "250 × 140",
    "image": "images/prod_img_22.jpg",
    "heroImage": "images/inprod_img_5.jpg",
    "detailImage": "images/inprod_img_0.jpg",
    "finish": "Honed / Sawn",
    "origin": "Iranian",
    "colors": "Black, Dark Grey",
    "description": "Very strong volcanic rock suitable for facades and interior design. Porous texture works well with cement mortar. Must be installed jointless."
  },
  {
    "id": 24,
    "code": "KK-G-124",
    "name": "Natanz Leathered Black Granite (Grade A)",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "280 × 190",
    "image": "images/stones/natanz-leathered-black-granite-grade-a.webp",
    "heroImage": "images/stones/natanz-leathered-black-granite-grade-a.webp",
    "detailImage": "images/stones/natanz-leathered-black-granite-grade-a-detail.webp",
    "finish": "Leathered",
    "origin": "Iranian",
    "colors": "Black",
    "description": "High hardness and acid-resistant granite. Ideal for kitchens, restrooms, exterior facades, and interior design."
  },
  {
    "id": 25,
    "code": "KK-C-125",
    "name": "Diamond Silk Crystal",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "270 × 175",
    "image": "images/stones/diamond-silk-crystal.webp",
    "heroImage": "images/stones/diamond-silk-crystal.webp",
    "detailImage": "images/stones/diamond-silk-crystal-detail.webp",
    "finish": "Silk / Polished",
    "origin": "Iranian",
    "colors": "Grey, White",
    "description": "Beautiful crystal structure that sparkles like a gem under lighting."
  },
  {
    "id": 26,
    "code": "KK-G-126",
    "name": "White Natanz Lineal",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "300 × 135",
    "image": "images/stones/white-natanz-lineal.webp",
    "heroImage": "images/stones/white-natanz-lineal.webp",
    "detailImage": "images/stones/white-natanz-lineal-detail.webp",
    "finish": "Lineal",
    "origin": "Iranian",
    "colors": "White, Grey",
    "description": "Granite with lineal grooved texture, perfect for interior design and modern facades."
  },
  {
    "id": 27,
    "code": "KK-G-127",
    "name": "Birjand Leathered Green Granite",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "285 × 170",
    "image": "images/prod_img_26.jpg",
    "heroImage": "images/inprod_img_3.jpg",
    "detailImage": "images/inprod_img_4.jpg",
    "finish": "Leathered",
    "origin": "Iranian",
    "colors": "Green, Dark Green",
    "description": "Unique green leathered granite suitable for exterior facades and interior feature walls."
  },
  {
    "id": 28,
    "code": "KK-Q-128",
    "name": "Black Tempest",
    "cat": "Quartzite",
    "stoneType": "Quartzite",
    "size": "325 × 195",
    "image": "images/stones/black-tempest-leathered.webp",
    "heroImage": "images/stones/black-tempest-leathered.webp",
    "detailImage": "images/stones/black-tempest-leathered-detail.webp",
    "finish": "Leathered / Polished",
    "origin": "Brazilian",
    "colors": "Black, Grey",
    "description": "Brazilian quartzite suited for kitchens, facades, and luxury interior design."
  },
  {
    "id": 29,
    "code": "KK-Q-129",
    "name": "Oreo",
    "cat": "Quartzite",
    "stoneType": "Quartzite",
    "size": "325 × 195",
    "image": "images/stones/oreo.webp",
    "heroImage": "images/stones/oreo.webp",
    "detailImage": "images/stones/oreo-detail.webp",
    "finish": "Polished",
    "origin": "Brazilian",
    "colors": "Gold, Blue, Brown",
    "description": "Exotic Brazilian quartzite suitable for modern interior design and building facades."
  },
  {
    "id": 30,
    "code": "KK-C-130",
    "name": "Eject Blue",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "280 × 165",
    "image": "images/prod_img_29.jpg",
    "heroImage": "images/inprod_img_0.jpg",
    "detailImage": "images/inprod_img_1.jpg",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Blue, Light Blue, Grey",
    "description": "High-contrast blue crystal stone that adds a distinct artistic feel to interior spaces."
  },
  {
    "id": 31,
    "code": "KK-C-131",
    "name": "Prada Crystal",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "290 × 180",
    "image": "images/stones/prada.webp",
    "heroImage": "images/stones/prada.webp",
    "detailImage": "images/stones/prada-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Cream, Light Beige",
    "description": "Cream-colored crystal stone with fine parallel lines, primarily crafted for interior design."
  },
  {
    "id": 32,
    "code": "KK-G-132",
    "name": "Black Beauty Lineal",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "290 × 190",
    "image": "images/stones/black-beauty-lineal.webp",
    "heroImage": "images/stones/black-beauty-lineal.webp",
    "detailImage": "images/stones/black-beauty-lineal-detail.webp",
    "finish": "Lineal",
    "origin": "Iranian",
    "colors": "Black, Gold",
    "description": "Extremely durable granite with a lineal textured pattern for a modern look. Distinguishes exterior facades and interior designs."
  },
  {
    "id": 33,
    "code": "KK-M-133",
    "name": "Persian Silk",
    "cat": "Marble",
    "stoneType": "Marble",
    "size": "175 × 150",
    "image": "images/stones/persian-silk.webp",
    "heroImage": "images/stones/persian-silk.webp",
    "detailImage": "images/stones/persian-silk-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Grey, Light Grey",
    "description": "Popular in global markets for modern architecture. Elegant grey tone makes it an ideal choice for interior design."
  },
  {
    "id": 34,
    "code": "KK-M-134",
    "name": "Marble Rose",
    "cat": "Marble",
    "stoneType": "Marble",
    "size": "260 × 160",
    "image": "images/prod_img_33.jpg",
    "heroImage": "images/inprod_img_4.jpg",
    "detailImage": "images/inprod_img_5.jpg",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Pink, Rose, Peach",
    "description": "Distinctive color palette compared to other market marbles, creating charming interior spaces."
  },
  {
    "id": 35,
    "code": "KK-G-135",
    "name": "Indian Black Forest",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "270 × 200",
    "image": "images/stones/black-forest.webp",
    "heroImage": "images/stones/black-forest.webp",
    "detailImage": "images/stones/black-forest-detail.webp",
    "finish": "Polished",
    "origin": "Indian",
    "colors": "Black, White Veins",
    "description": "High quality granite resistant to abrasion and acid cleaners, suitable for all interior and exterior uses."
  },
  {
    "id": 36,
    "code": "KK-G-136",
    "name": "Volga Blue",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "328 × 200",
    "image": "images/stones/volga-blue.webp",
    "heroImage": "images/stones/volga-blue.webp",
    "detailImage": "images/stones/volga-blue-detail.webp",
    "finish": "Polished",
    "origin": "Ukrainian / Imported",
    "colors": "Black, Blue Labradorite",
    "description": "World-renowned granite with vibrant blue iridescence set in a black background. Highly resistant to abrasion and acids."
  },
  {
    "id": 37,
    "code": "KK-G-137",
    "name": "Leathered Green Granite",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "266 × 180",
    "image": "images/stones/leathered-green-granite.webp",
    "heroImage": "images/stones/leathered-green-granite.webp",
    "detailImage": "images/stones/leathered-green-granite-detail.webp",
    "finish": "Leathered",
    "origin": "Iranian",
    "colors": "Green",
    "description": "Leathered finish green granite expressing power and luxury in facade and interior design."
  },
  {
    "id": 38,
    "code": "KK-T-138",
    "name": "Cream Leathered Travertine",
    "cat": "Travertine",
    "stoneType": "Travertine",
    "size": "220 × 170",
    "image": "images/stones/cream-leathered-travertine.webp",
    "heroImage": "images/stones/cream-leathered-travertine.webp",
    "detailImage": "images/stones/cream-leathered-travertine-detail.webp",
    "finish": "Leathered",
    "origin": "Iranian",
    "colors": "Cream, Beige",
    "description": "Widely used in minimalist interior and exterior designs, imparting a serene cream aesthetic."
  },
  {
    "id": 39,
    "code": "KK-T-139",
    "name": "Cream Raw Vein-Cut Travertine",
    "cat": "Travertine",
    "stoneType": "Travertine",
    "size": "275 × 170",
    "image": "images/prod_img_38.jpg",
    "heroImage": "images/inprod_img_3.jpg",
    "detailImage": "images/inprod_img_4.jpg",
    "finish": "Raw / Vein-Cut",
    "origin": "Iranian",
    "colors": "Cream, Ivory",
    "description": "Unfilled / raw vein-cut travertine favoured for minimal style facades and interiors."
  },
  {
    "id": 40,
    "code": "KK-T-140",
    "name": "Tiramisu Travertine",
    "cat": "Travertine",
    "stoneType": "Travertine",
    "size": "280 × 170",
    "image": "images/prod_img_39.jpg",
    "heroImage": "images/inprod_img_4.jpg",
    "detailImage": "images/inprod_img_5.jpg",
    "finish": "Honed / Leathered",
    "origin": "Iranian",
    "colors": "Cream, Warm Brown",
    "description": "Warm-toned travertine for modern and minimalist interior and exterior designs."
  },
  {
    "id": 41,
    "code": "KK-G-141",
    "name": "Patagonia Black",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "330 × 200",
    "image": "images/prod_img_40.jpg",
    "heroImage": "images/inprod_img_5.jpg",
    "detailImage": "images/inprod_img_0.jpg",
    "finish": "Polished",
    "origin": "Brazilian",
    "colors": "Black, White, Translucent Quartz",
    "description": "Extremely rare Brazilian granite featuring exceptionally large crystal grain structure unlike any other stone in the world."
  },
  {
    "id": 42,
    "code": "KK-Q-142",
    "name": "Jacaranda",
    "cat": "Quartzite",
    "stoneType": "Quartzite",
    "size": "310 × 185",
    "image": "images/prod_img_41.jpg",
    "heroImage": "images/inprod_img_0.jpg",
    "detailImage": "images/inprod_img_1.jpg",
    "finish": "Polished",
    "origin": "Brazilian",
    "colors": "Multicolor, Red, Gold, Grey",
    "description": "Exotic Brazilian quartzite with artistic patterns and fine crystal grain that sparkles brilliantly under light."
  },
  {
    "id": 43,
    "code": "KK-G-143",
    "name": "Turquoise Granite",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "305 × 175",
    "image": "images/stones/turquoise-granite.webp",
    "heroImage": "images/stones/turquoise-granite.webp",
    "detailImage": "images/stones/turquoise-granite-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Turquoise, Blue, Green",
    "description": "Rare blue-turquoise granite creating statement interior design elements."
  },
  {
    "id": 44,
    "code": "KK-M-144",
    "name": "Golden Olive",
    "cat": "Marble",
    "stoneType": "Marble",
    "size": "285 × 175",
    "image": "images/prod_img_43.jpg",
    "heroImage": "images/inprod_img_2.jpg",
    "detailImage": "images/inprod_img_3.jpg",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Cream, Olive, Gold",
    "description": "Uniform cream-toned marble with subtle olive hue for warm interior design."
  },
  {
    "id": 45,
    "code": "KK-M-145",
    "name": "Persian Scato",
    "cat": "Marble",
    "stoneType": "Marble",
    "size": "285 × 165",
    "image": "images/stones/chini-scato.webp",
    "heroImage": "images/stones/chini-scato.webp",
    "detailImage": "images/stones/chini-scato-detail.webp",
    "finish": "Polished / Honed",
    "origin": "Iranian",
    "colors": "Grey, Beige",
    "description": "Uniform texture and tone, heavily preferred in minimal and contemporary space designs."
  },
  {
    "id": 46,
    "code": "KK-C-146",
    "name": "Thassos White",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "270 × 150",
    "image": "images/stones/thassos.webp",
    "heroImage": "images/stones/thassos.webp",
    "detailImage": "images/stones/thassos-detail.webp",
    "finish": "Polished",
    "origin": "Greek",
    "colors": "Pure White",
    "description": "One of the whitest natural stones globally, prized for interior design and fine sculpting."
  },
  {
    "id": 47,
    "code": "KK-C-147",
    "name": "Jaguar Crystal",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "260 × 175",
    "image": "images/stones/jaguar.webp",
    "heroImage": "images/stones/jaguar.webp",
    "detailImage": "images/stones/jaguar-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "White, Black, Pink",
    "description": "Distinctive crystal structure blending white, black, and pink tones. Popular for interior feature accents."
  },
  {
    "id": 48,
    "code": "KK-Q-148",
    "name": "Magma Gold",
    "cat": "Quartzite",
    "stoneType": "Quartzite",
    "size": "325 × 195",
    "image": "images/prod_img_47.jpg",
    "heroImage": "images/inprod_img_0.jpg",
    "detailImage": "images/inprod_img_1.jpg",
    "finish": "Polished",
    "origin": "Brazilian",
    "colors": "Black, Gold, Orange",
    "description": "High-end Brazilian quartzite with dramatic golden and amber veins."
  },
  {
    "id": 49,
    "code": "KK-G-149",
    "name": "Rock Alpinus",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "295 × 158",
    "image": "images/stones/alpinus-rock.webp",
    "heroImage": "images/stones/alpinus-rock.webp",
    "detailImage": "images/stones/alpinus-rock-detail.webp",
    "finish": "Rock Finish / 3D Textured",
    "origin": "Iranian",
    "colors": "Cream, Brown, Black",
    "description": "Coarse-grained granite. Rock design finish highlights mineral structures into 3D geometric relief."
  },
  {
    "id": 50,
    "code": "KK-B-150",
    "name": "Light Mars Andesite",
    "cat": "Basalt",
    "stoneType": "Andesite",
    "size": "260 × 150",
    "image": "images/prod_img_49.jpg",
    "heroImage": "images/inprod_img_2.jpg",
    "detailImage": "images/inprod_img_3.jpg",
    "finish": "Honed / Matte",
    "origin": "Iranian",
    "colors": "Concrete Grey, Light Slate",
    "description": "Extremely robust volcanic rock with concrete-like texture and appearance."
  },
  {
    "id": 51,
    "code": "KK-G-151",
    "name": "Matte Black Sea",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "300 × 180",
    "image": "images/stones/matte-blacksea.webp",
    "heroImage": "images/stones/matte-blacksea.webp",
    "detailImage": "images/stones/matte-blacksea-detail.webp",
    "finish": "Matte / Honed",
    "origin": "Iranian",
    "colors": "Black, White",
    "description": "Black granite with white veins and hidden sparkling crystals in its matte background, delivering a luxury aesthetic."
  },
  {
  "id": 52,
  "code": "KK-G-152",
  "name": "Natanz White Cotton",
  "cat": "Granite",
  "stoneType": "Granite",
  "size": "285 × 185",
  "image": "images/prod_img_7.jpg",
  "heroImage": "images/inprod_img_1.jpg",
  "detailImage": "images/inprod_img_2.jpg",
  "finish": "Cotton",
  "origin": "Iran",
  "colors": "White, Light Grey",
  "description": "White granite from Natanz with a clean and uniform texture. Enhanced with a Cotton finish, it offers a refined appearance and subtle surface character. Suitable for both interior and exterior applications, including flooring, wall cladding, facades, stairs, and other architectural spaces."
},
{
  "id": 53,
  "code": "KK-G-153",
  "name": "Natanz White Scratch",
  "cat": "Granite",
  "stoneType": "Granite",
  "size": "270 × 160",
  "image": "images/stones/scratch-white-natanz.webp",
  "heroImage": "images/stones/scratch-white-natanz.webp",
  "detailImage": "images/stones/scratch-white-natanz-detail.webp",
  "finish": "Scratch",
  "origin": "Iran",
  "colors": "White, Light Grey",
  "description": "White granite from Natanz featuring a clean and uniform texture. Processed with a Scratch finish, it offers a distinctive linear surface that enhances its natural appearance. Suitable for both interior and exterior applications, including flooring, wall cladding, facades, stairs, and other architectural spaces."
},
{
  "id": 54,
  "code": "KK-M-154",
  "name": "Cream Marble Lineal",
  "cat": "Marble",
  "stoneType": "Marble",
  "size": "290 × 182",
  "image": "images/stones/cream-marble-lineal-plus.webp",
  "heroImage": "images/stones/cream-marble-lineal-plus.webp",
  "detailImage": "images/stones/cream-marble-lineal-plus-detail.webp",
  "finish": "Lineal",
  "origin": "Iran",
  "colors": "Cream, Beige",
  "description": "Cream marble featuring a clean texture and a warm natural tone. Finished with a Lineal surface treatment, it offers a distinctive linear appearance that enhances its elegance. Ideal for interior applications, including flooring, wall cladding, stairs, and other architectural spaces."
},
{
  "id": 55,
  "code": "KK-G-155",
  "name": "Leathered Black Diamond",
  "cat": "Granite",
  "stoneType": "Granite",
  "size": "285 × 190",
  "image": "images/stones/black-diamond-leather.webp",
  "heroImage": "images/stones/black-diamond-leather.webp",
  "detailImage": "images/stones/black-diamond-leather-detail.webp",
  "finish": "Leathered",
  "origin": "Angola",
  "colors": "Black, Dark Grey, White Crystal",
  "description": "Black Diamond granite from Angola features a striking black background with large natural crystals. Finished with a Leathered surface, it offers a rich texture and refined appearance while maintaining exceptional durability. Suitable for both interior and exterior applications, including flooring, wall cladding, countertops, facades, stairs, and other architectural spaces."
},
  {
    "id":56,
    "code": "KK-G-156",
    "name": "Tuyserkan Honed Granite",
    "cat": "Granite",
    "stoneType": "Granite",
    "size": "333 × 170",
    "image": "images/stones/tuyserkan-honed-granite.webp",
    "heroImage": "images/stones/tuyserkan-honed-granite.webp",
    "detailImage": "images/stones/tuyserkan-honed-granite-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "Black, Dark Grey",
    "description": "Chemical-resistant Iranian granite ideal for walls, stairs, courtyard floors, parking lots, and building facades."
  },
  {
  "id": 57,
  "code": "KK-M-157",
  "name": "Golden Rose",
  "cat": "Marble",
  "stoneType": "Marble",
  "size": "270 × 155",
  "image": "images/stones/golden-rose.webp",
  "heroImage": "images/stones/golden-rose.webp",
  "detailImage": "images/stones/golden-rose-detail.webp",
  "finish": "Polished",
  "origin": "Iran",
  "colors": "Red, Golden, White Veins",
  "description": "Golden Rose marble features a rich red background accented with elegant golden and white veining. Its polished surface enhances the stone’s natural beauty, making it an excellent choice for interior applications, including flooring, wall cladding, stairs, feature walls, and other architectural spaces."
},
  {
    "id": 58,
    "code": "KK-C-158",
    "name": "Azna",
    "cat": "Marble",
    "stoneType": "Crystal",
    "size": "305 × 185",
    "image": "images/stones/chini-azna.webp",
    "heroImage": "images/stones/chini-azna.webp",
    "detailImage": "images/stones/chini-azna-detail.webp",
    "finish": "Polished",
    "origin": "Iranian",
    "colors": "White, Light Grey",
    "description": "One of the finest options for interior flooring."
  },
];

export function getProduct(id: number): Product {
  return PRODUCTS.find(p => p.id === id) ?? PRODUCTS[0];
}
